Models/CardsApi.cs
namespace Deck_of_Cards_API.Models
{
    public class CardsApi
    {
        public string image { get; set; }

        public string value { get; set; }

        public string suit { get; set; }

    }
}

Models/DrawFive.cs
namespace Deck_of_Cards_API.Models
{
    public class DrawFive
    {
        public bool success { get; set; }

        public string deck_id { get; set; }

        public CardsApi cards { get; set; } 

        public List<CardsApi> cards_drawn { get; set; }
    }
}

Models/DrawFiveApi.cs
namespace Deck_of_Cards_API.Models
{
    public class DrawFiveApi
    {
        public bool success { get; set; }

        public string deck_id { get; set; }

     

        public List<CardsApi> cards { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace Deck_of_Cards_API.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/GenerateDeck.cs
namespace Deck_of_Cards_API.Models
{
    public class GenerateDeck
    {
        public bool success { get; set; }

        public string deck_id { get; set; }

        public int remaining { get; set; }
        
        public bool shuffled { get; set; }

    }
}

Controllers/DeckOfCardsController.cs
using Flurl.Http;
using Microsoft.AspNetCore.Mvc;
using Deck_of_Cards_API.Models;

namespace Deck_of_Cards_API.Controllers
{
    public class DeckOfCardsController : Controller
    {
        public IActionResult Index()
        {
            return RedirectToAction("Details");
        }



        public IActionResult Details(string deck_id)
        {
            string apiUrl = "https://deckofcardsapi.com/api/deck/new/shuffle";
            var apiTask = apiUrl.GetJsonAsync<GenerateDeck>();
            apiTask.Wait();
            GenerateDeck result = apiTask.Result;

             apiUrl = $"https://deckofcardsapi.com/api/deck/{result.deck_id}/draw/?count=5";
            var apiTaskCard = apiUrl.GetJsonAsync<DrawFiveApi>();
            apiTaskCard.Wait();
            DrawFiveApi resultCards = apiTaskCard.Result;

            return View("CardsDetails", resultCards.cards);

        }








    }
}

Controllers/HomeController.cs
using Deck_of_Cards_API.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Deck_of_Cards_API.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/DeckOfCards/CardsDetails.cshtml
@model IEnumerable<Deck_of_Cards_API.Models.CardsApi>

@{
    ViewData["Title"] = "CardsDetails";
}

<h1>Cards drawn...</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.value)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.suit)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="@item.image"/>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.value)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.suit)
                </td>
                
            </tr>
        }
    </tbody>
</table>

Views/DeckOfCards/GenerateDeck.cshtml
@{
    ViewData["Title"] = "GenerateDeck";
}

<h1>GenerateDeck</h1>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>To make a new deck, click above...</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Deck_of_Cards_API</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Deck_of_Cards_API.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Deck_of_Cards_API</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DeckOfCards" asp-action="Details">Make a deck!</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Deck_of_Cards_API - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>